project_id = "mvgkutrlfmmuioabfkce"

[functions.azure-openai-chat]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false

[functions.crop-recommender]
verify_jwt = false

[functions.farmer-ai-assistant]
verify_jwt = false

[functions.chatbot-brain]
verify_jwt = false

[functions.xai-grok-chat]
verify_jwt = false